// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Datasource URLs are defined in `schema.prisma` so we can support both:
  // - DATABASE_URL (runtime / pooled)
  // - DIRECT_URL (migrations / non-pooled)
});
